services:
  prestashop:
    image: prestashop/prestashop:8
    environment:
      PS_INSTALL_AUTO: "1"
      PS_DOMAIN: myshop.metrocart.store
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: ${DB_PASSWD}
      ADMIN_MAIL: aboelyoos@gmail.com
      ADMIN_PASSWD: Changeme!
      PS_COUNTRY: US
      PS_LANGUAGE: en
    volumes:
      - prestashop_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: ${DB_PASSWD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  prestashop_data:
  db_data:
